name: chatters_shared
description: Shared Flutter code for the Chatters Android and iOS apps.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  flutter_secure_storage: ^9.2.2
  pointycastle: ^3.9.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  connectivity_plus: ^6.0.5
  flutter_local_notifications: ^18.0.1
  intl: any
  flutter_webrtc: ^1.6.2+hotfix.3
  device_info_plus: ^12.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-ExtraBold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
